import type { Metadata } from "next";                                                                                                                                                
 import { Geist, Geist_Mono } from "next/font/google";                                                                                                                                
 import { Poppins } from "next/font/google";                                                                                                                                          
 import "./globals.css";                                                                                                                                                              
                                                                                                                                                                                      
 const geistSans = Geist({                                                                                                                                                            
   variable: "--font-geist-sans",                                                                                                                                                     
   subsets: ["latin"],                                                                                                                                                                
 });                                                                                                                                                                                  
                                                                                                                                                                                      
 const geistMono = Geist_Mono({                                                                                                                                                       
   variable: "--font-geist-mono",                                                                                                                                                     
   subsets: ["latin"],                                                                                                                                                                
 });                                                                                                                                                                                  
                                                                                                                                                                                      
 const poppins = Poppins({                                                                                                                                                            
   weight: ["400", "700"],                                                                                                                                                            
   variable: "--font-poppins",                                                                                                                                                        
   subsets: ["latin"],                                                                                                                                                                
 });                                                                                                                                                                                  
                                                                                                                                                                                      
 export const metadata: Metadata = {                                                                                                                                                  
   title: "Create Next App",                                                                                                                                                          
   description: "Generated by create next app",                                                                                                                                       
 };                                                                                                                                                                                   
                                                                                                                                                                                      
 export default function RootLayout({                                                                                                                                                 
   children,                                                                                                                                                                          
 }: {                                                                                                                                                                                 
   children: React.ReactNode;                                                                                                                                                         
 }) {                                                                                                                                                                                 
   return (                                                                                                                                                                           
     <html lang="en" suppressHydrationWarning>                                                                                                                                                                 
       <body                                                                                                                                                                          
         className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased min-h-screen bg-white dark:bg-black text-gray-800 dark:text-gray-100`}               
       >                                                                                                                                                                              
         {/* Fancy Top Nav */}                                                                                                                                                        
         <header className="w-full bg-gradient-to-r from-blue-500 to-blue-700 bg-opacity-80 backdrop-filter backdrop-blur-lg px-8 py-4 shadow-lg fixed top-0 z-50">                   
           <nav className="max-w-7xl mx-auto flex items-center justify-between">                                                                                                      
             <div className="font-bold text-lg text-white" style={{ fontFamily: 'Poppins, sans-serif' }}>                                                                             
               CryptoMatic with AI                                                                                                                                                    
             </div>                                                                                                                                                                   
             <div className="space-x-4">                                                                                                                                              
               <a href="/" className="text-white hover:text-blue-300 transition duration-300 ease-in-out transform hover:scale-105">                                                  
                 Home                                                                                                                                                                 
               </a>                                                                                                                                                                   
               <a href="/train" className="text-white hover:text-blue-300 transition duration-300 ease-in-out transform hover:scale-105">                                             
                 Train                                                                                                                                                                
               </a>                                                                                                                                                                   
               <a href="/paper-trading" className="text-white hover:text-blue-300 transition duration-300 ease-in-out transform hover:scale-105">                                     
                 Paper Trade                                                                                                                                                          
               </a>                                                                                                                                                                   
             </div>                                                                                                                                                                   
           </nav>                                                                                                                                                                     
         </header>                                                                                                                                                                    
                                                                                                                                                                                      
         <main className="max-w-4xl mx-auto px-4 py-6 mt-16">                                                                                                                         
           {children}                                                                                                                                                                 
         </main>                                                                                                                                                                      
       </body>                                                                                                                                                                        
     </html>                                                                                                                                                                          
   );                                                                                                                                                                                 
 }                      
